### ISSUE TITLE
Can you up video once again because its copyrighted by youtube?

### ISSUE THREAD

**Issue by kiritohuy1208** [sujitmohanty/shopit-mern#1]
hello, I am learning your course about create shopit-mern on youtube videos. But your video is copyrighted, so Can you up video once againt, thks you so much. Your video  is really essay understand and i like it.

**Comment by sujitmohanty** [comment]
Hi  Tô Quang Huy 

Can you please share the link to video that you talking about  and how did you find my repository?

**Comment by sujitmohanty** [comment]
> 
> 
> hello, I am learning your course about create shopit-mern on youtube videos. But your video is copyrighted, so Can you up video once againt, thks you so much. Your video is really essay understand and i like it.

Hi Tô Quang Huy

Can you please share the link to video that you talking about and how did you find my repository?

**Comment by kiritohuy1208** [comment]
This is link video : https://www.youtube.com/watch?v=J7l5ZIXY5EQ&list=PLL4mtmkTOEwTeq8BRFWUkceeZUDylhDoF
I have find your video on youtube that is teach about mern stack, build shopit  project and deploy it heroku, course about 125 video, and under video's description , have attach link demo to github, So that, i find your repository. Currently, I have learning 50 backend video. I hope you can help me, thks so much.

**Comment by sujitmohanty** [comment]
> 
> 
> This is link video : https://www.youtube.com/watch?v=J7l5ZIXY5EQ&list=PLL4mtmkTOEwTeq8BRFWUkceeZUDylhDoF
> I have find your video on youtube that is teach about mern stack, build shopit project and deploy it heroku, course about 125 video, and under video's description , have attach link demo to github, So that, i find your repository. Currently, I have learning 50 backend video. I hope you can help me, thks so much.

Hi Dear, please check this - https://github.com/sujitmohanty/shopit-mern/blob/master/readme.md
It contains the link to the full course by the original which is neither me nor the person who published the stolen work on YouTube. That is why the channel got deleted.
The course author is an amazing teacher and is very active and prompt in the course forums to resolve any course related doubts. I highly recommend purchasing and enrolling for the course. You will have an amazing experience. It's the BEST MERN course on Udemy.
